"""Domain helpers and business rules.

The HTTP and MCP adapters call functions in this package so product rules are
implemented in one place.
"""

from app.domain.constants import FOOD_NAME_SIMILARITY_THRESHOLD
from app.domain.day_aggregation import get_day, get_range
from app.domain.dto import (
    AppSettingsDTO,
    DayMealGroup,
    DayResponse,
    EffectiveTarget,
    EnergyEvent,
    EnergyPoint,
    EnergyTimeline,
    FoodCandidate,
    FuelingFlag,
    ItemMacros,
    ManualCaloriesOutResult,
    MealItemMatch,
    MealItemResponse,
    MealItemSpec,
    MealResponse,
    PeriodTotals,
    PlannedWorkoutDTO,
    RangeResponse,
    SetTargetResult,
    SyncIntervalsResult,
    SyncStatus,
    TargetRow,
    TemplateItemResponse,
    TemplateItemSpec,
    TemplateResponse,
)
from app.domain.energy_balance import compute_energy_timeline
from app.domain.errors import (
    AdhocItemNameRequiredError,
    DomainError,
    FoodAmbiguousError,
    FoodDuplicateError,
    FoodMergeSameFoodError,
    FoodNotFoundError,
    IntervalsUnavailableError,
    InvalidTimezoneError,
    MealItemFoodLinkedError,
    MealItemMacrosRequiredError,
    MealItemNotFoundError,
    MealNotFoundError,
    NaiveDatetimeError,
    NoTargetSetError,
    ServingUnitImmutableError,
    TemplateNotFoundError,
    UnauthorizedError,
)
from app.domain.food_resolution import resolve_food
from app.domain.foods import (
    AddFoodResult,
    FindFoodsResult,
    FoodSearchResult,
    MergeFoodResult,
    UpdateFoodResult,
    add_food,
    delete_food,
    find_foods,
    merge_food,
    search_foods,
    set_favorite_food,
    update_food,
)
from app.domain.intervals_sync import get_sync_status, set_manual_calories_out, sync_intervals
from app.domain.meal_copying import copy_meal
from app.domain.meal_deletion import delete_meal, delete_meal_item
from app.domain.meal_editing import update_meal, update_meal_item
from app.domain.meal_logging import log_meal
from app.domain.meal_search import find_meal
from app.domain.meal_timing import (
    infer_meal_type,
    localize_naive_datetime,
    parse_local_date,
    resolve_meal_type,
)
from app.domain.nutrition_math import (
    UnitNormalizationError,
    compute_item_macros,
    normalize_to_grams,
)
from app.domain.planned_workouts import create_manual_planned_workout
from app.domain.settings import get_settings, update_settings
from app.domain.targets import get_effective_target, list_targets, set_target
from app.domain.templates import (
    create_template,
    delete_template,
    list_templates,
    log_template,
    update_template,
)

__all__ = [
    "FOOD_NAME_SIMILARITY_THRESHOLD",
    "AddFoodResult",
    "AdhocItemNameRequiredError",
    "AppSettingsDTO",
    "DayMealGroup",
    "DayResponse",
    "DomainError",
    "EffectiveTarget",
    "EnergyEvent",
    "EnergyPoint",
    "EnergyTimeline",
    "FindFoodsResult",
    "FoodAmbiguousError",
    "FoodCandidate",
    "FoodDuplicateError",
    "FoodMergeSameFoodError",
    "FoodNotFoundError",
    "FoodSearchResult",
    "FuelingFlag",
    "IntervalsUnavailableError",
    "InvalidTimezoneError",
    "ItemMacros",
    "ManualCaloriesOutResult",
    "MealItemFoodLinkedError",
    "MealItemMacrosRequiredError",
    "MealItemMatch",
    "MealItemNotFoundError",
    "MealItemResponse",
    "MealItemSpec",
    "MealNotFoundError",
    "MealResponse",
    "MergeFoodResult",
    "NaiveDatetimeError",
    "NoTargetSetError",
    "PeriodTotals",
    "PlannedWorkoutDTO",
    "RangeResponse",
    "ServingUnitImmutableError",
    "SetTargetResult",
    "SyncIntervalsResult",
    "SyncStatus",
    "TargetRow",
    "TemplateItemResponse",
    "TemplateItemSpec",
    "TemplateNotFoundError",
    "TemplateResponse",
    "UnauthorizedError",
    "UnitNormalizationError",
    "UpdateFoodResult",
    "add_food",
    "compute_energy_timeline",
    "compute_item_macros",
    "copy_meal",
    "create_manual_planned_workout",
    "create_template",
    "delete_food",
    "delete_meal",
    "delete_meal_item",
    "delete_template",
    "find_foods",
    "find_meal",
    "get_day",
    "get_effective_target",
    "get_range",
    "get_settings",
    "get_sync_status",
    "infer_meal_type",
    "list_targets",
    "list_templates",
    "localize_naive_datetime",
    "log_meal",
    "log_template",
    "merge_food",
    "normalize_to_grams",
    "parse_local_date",
    "resolve_food",
    "resolve_meal_type",
    "search_foods",
    "set_favorite_food",
    "set_manual_calories_out",
    "set_target",
    "sync_intervals",
    "update_food",
    "update_meal",
    "update_meal_item",
    "update_settings",
    "update_template",
]
